version: "3.9"
volumes:
  php-fpm-socket:
  db-store:
  psysh-store:
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./src
        target: /work/src
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - target: 80
        published: ${WEB_PORT}
        protocol: tcp
        mode: host
      - "443:443" #for ssl
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./src
        target: /work/src

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${DB_PORT}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
  # minio:
  #   image: 'minio/minio'
  #   container_name: minio
  #   environment:
  #     MINIO_ROOT_USER: minioadminuser
  #     MINIO_ROOT_PASSWORD: minioadminpassword
  #   entrypoint: bash
  #   command: -c "/opt/bin/minio server /export --address :9999 --console-address :9001"
  #   volumes:
  #     - ./docker/minio/data:/export
  #   ports:
  #     - '9000:9999'
  #     - '9001:9001'

  # smtp:
  #   build: docker/smtp
  #   ports:
  #     - 1080:1080
  #   environment:
  #     TZ: Asia/Tokyo
